### ISSUE TITLE
Multiple servers in config

### ISSUE THREAD

**Issue by biosoup** [screepers/screeps-multimeter#15]
Could it be made possible for multiple configurations, to select on start/via parameter for which server to launch multimeter?

Like having:
1. mmo
2. s+
3. s+2
etc.

**Comment by CGamesPlay** [comment]
Hello, thanks for submitting an issue! I think this is a great idea, and I think a parameter is a great way to do it. I'd be happy to accept a pull request that implemented this functionality. Here's what I would do:

- Use a library like [dashdash](https://github.com/trentm/node-dashdash) or [yargs](https://github.com/yargs/yargs) to add support for a `-C, --config` argument.
- Modify the `config_manager.js` file to take a specific config file path, and create a `locateDefaultConfig` method to autodetect it if nothing is specified`.

If you want to take a stab at this, I think it could definitely be accepted.

Thanks again for your interest in multimeter!

**Comment by SystemParadox** [comment]
This is now possible with multimeter 2.0.0, using the screeps unified config file format.
