### ISSUE TITLE
Cannot npm install, native deps failing to build

### ISSUE THREAD

**Issue by Ramblurr** [screepers/screeps-multimeter#33]
On a fresh checkout of this repo if I do `npm install`, it fails when building the native bit of the bufferutil dependency:

sample:
```
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  124 |     assert(wrap->handle_.IsNearDeath());
      |  
```
full log here: https://gist.github.com/Ramblurr/57b57b6bcb40ae21944ff4c94e34d128

This is on node version v12.16.1.

Is a particular version of node needed?

**Comment by djD-REK** [comment]
Most Screeps tools need node v10

Best regards,
Derek

Derek R. Austin, PT, DPT, MS, BCTMB, LMT, CSCS


Join me on LinkedIn: https://www.linkedin.com/in/derek-austin/

**Comment by Ramblurr** [comment]
Did not know that.

**Comment by SystemParadox** [comment]
`screeps-api` needs to update their bufferutil dependency to fix this:

https://github.com/screepers/node-screeps-api/issues/54

Interestingly if you install node10, npm install, then install node12, it runs fine - so either we're not doing anything that uses `nan` or it's literally just a build problem.

**Comment by SystemParadox** [comment]
Actually it seems that you can even install this with node12 and ignore the errors, multimeter still works. I notice that `bufferutil` is listed as an optional dependency for `screeps-api`.

**Comment by Ramblurr** [comment]
Thanks for looking into this! Getting it working with node12 without errors would be very handy. Seems (from your other comment) that those optional deps aren't even used and could just be removed?

**Comment by SystemParadox** [comment]
screeps-api has updated to 1.12.2 which fixes this. You should just be able to run `npm update` to get the new version.
