### ISSUE TITLE
Allow use on private servers

### ISSUE THREAD

**Issue by Dessix** [screepers/screeps-multimeter#4]
Screeps-Api recently added support for use on private servers:
https://github.com/screepers/node-screeps-api/commit/60acc9663cd38666be561005f3e69ccd312ab498

**Comment by CGamesPlay** [comment]
Hey, thanks for the interest in the project! I would be happy to accept a pull request that bumped the version of screeds-api and then added this as an option. It shouldn't be too hard to do, in fact I have a diff that allows you to use PTR that you can follow to add support for any other server:

https://github.com/screepers/screeps-multimeter/compare/demo-ptr

**Comment by CGamesPlay** [comment]
Closed in #5.
